### ISSUE TITLE
Improvements for iOS tracebacks / dSYM upload confusion

### ISSUE THREAD

**Issue by sterlingwes** [rollbar/rollbar-ios#148]
Hello! I threatened in https://github.com/rollbar/rollbar-ios/issues/52 that I'd open a reproduction repo to highlight some of the issues I'm having with getting setup with iOS on rollbar, so here it is 😶:

https://github.com/sterlingwes/rn-rollbar-repro

Hopefully the readme provides enough context along with the intercom history I have with @jessicahsieh who's been trying to help me sort out my issues since mid-December:

- [x] https://github.com/rollbar/rollbar-ios/issues/145 (mostly solved, just needs another release)
- [ ] iOS tracebacks collapsing project frames as "non-project"
- [ ] `(unknown)` items complaining it couldn't be symbolicated when I've verified the dSYMs were uploaded

The readme in the repo has additional reproduction steps. Please let me know if you need further clarification! 🙏

**Comment by jessewgibbs** [comment]
@sterlingwes thanks for all the details.

@akornich can you investigate this?

**Comment by akornich** [comment]
@sterlingwes , @jessewgibbs , since this one is directly related to #52 , i am reassigning it to @rokob - he is already looking into #52 and most likely will be forwarding both to the server-side team since both issues appear to be a server side glitch.

**Comment by sterlingwes** [comment]
Can I get an update on this one?

**Comment by rokob** [comment]
The issue _iOS tracebacks collapsing project frames as "non-project"_ happens when the stack trace is not symbolicated for whatever reason. The "unknown" items when there exists a valid dsym I have seen happen in two cases. One is some weird simulator timing thing where the crash report seems to get munged but does not actually happen in a real build on a real device.

The other is when an item gets fingerprinted to be the same as a previously unsymbolicated item, the grouping makes it look like the title is "unknown" when in fact digging in to the occurrence you see a real title with a symbolicated item. I am still trying to figure out exactly why this is happening, but it seems like it is partially correct to group them because they are the same, but the title needs to get updated once symbolication has happened.

**Comment by sterlingwes** [comment]
Thanks @rokob for the update 👍  That first issue (collapsing frames) seems to have resolved actually now that I look through our iOS items. I'm not sure what changed but I'm seeing our project now which is awesome.

Good to know RE: simulator. I'll close this until I can come up with more examples of the unsymbolicated items

**Comment by sterlingwes** [comment]
Is this the right place to open an issue / feature request for supporting multiple dSYM uploads? We're really missing symbolication for our dependencies which we took for granted on crashlytics

I imagine this is a backend thing

**Comment by jessewgibbs** [comment]
@sterlingwes we track feature requests for our web app in a different system.  I'll add this to our backlog and note that you requested it.
