### ISSUE TITLE
Crashes not getting logged as critical

### ISSUE THREAD

**Issue by prat14k** [rollbar/rollbar-ios#243]
Hi Rollbar Team,
We are using RollBar's error reporting service in our iOS app. We have successfully integrated Rollbar in the app and are able to see any warnings, error or crashes that arised. 
We used a property `crashLevel` in the `RollbarConfiguration` to set the level of reporting for crashes. This is done before initializing the Rollbar, as mentioned in the docs for iOS and macOS. 
But it is still reporting them as error. 

Occurences: https://rollbar.com/prateek_vin/ios-app/items/2/

Let me know if you need anything else

**Comment by prat14k** [comment]
Code snippet used for this: 
```
let config: RollbarConfiguration = RollbarConfiguration()    
config.environment = environment         
config.crashLevel = RollbarStringFromLevel(.critical)            
Rollbar.initWithAccessToken(Constants.rollbarAccessToken, configuration: config, enableCrashReporter: true)
```

**Comment by akornich** [comment]
hi @prat14k, your SDK usage pattern looks correct to me.
i think the confusion regarding error vs critical level rises due to the fact that the very first occurrence of this item came with the level set to `error`  so all the subsequent occurrences were grouped into the same item that already carried the `error` value (even that the subsequent occurrences were marked as `critical`). Here is the very first occurrence that brought in `error` classification: [https://rollbar.com/prateek_vin/ios-app/items/2/occurrences/113330004544/](https://rollbar.com/prateek_vin/ios-app/items/2/occurrences/113330004544/).
Does it make sense now?

**Comment by prat14k** [comment]
Hi @akornich, I get your point.
So I resolved the issue thread and then crashing it again, it showed as critical in the thread. 

Thanks for the clarification.
