### ISSUE TITLE
Warning: 'sendSynchronousRequest:returningResponse:error:' is deprecated.

### ISSUE THREAD

**Issue by pouriaalmassi** [rollbar/rollbar-ios#41]
## Description
The project's master branch currently generates a deprecation warning from the call `sendSynchronousRequest:returningResponse:error:`. 

- Does this request need to be sent synchronously? 
- Is there a reason we're using `NSURLConnection`? 

## Steps to Reproduce
1. Open the project.
1. Build.

## Expected Behaviour
- In the issue navigator you will see the following warning: 

```
RollbarNotifier.m:337:37: 'sendSynchronousRequest:returningResponse:error:' is deprecated: first deprecated in iOS 9.0 - Use [NSURLSession dataTaskWithRequest:completionHandler:] (see NSURLSession.h
```

**Comment by rokob** [comment]
Yikes yeah that is bad, the short answer to these questions is that this code is old. We are using NSURLConnection and sending a sync request because that was not the worst thing to do back when this was originally written. It would be great to get this updated to use NSURLSession. We are using the sync method because this is only ever executed on a separate background thread so that is probably just because it was easier to write the code that way rather than dealing with the delegate API of the async version. Ideally we convert to just using NSURLSession and let it handle the hard stuff. We also don't need to be spinning up our own thread and dealing with our own runloop handling, it would be better to just leverage GCD queues.

**Comment by rivkahstandig3636** [comment]
@rokob With the release of v1 will this still be an issue?

**Comment by rokob** [comment]
We no longer use this deprecated method on iOS 7+ so I think this is safe to close.
