### ISSUE TITLE
this crashes my app

### ISSUE THREAD

**Issue by freddyh** [rollbar/rollbar-ios#43]
NSMutableDictionary* data = [NSMutableDictionary new];
[data setObject:[CookieManager summary] forKey:@"cookies after"];
[Rollbar logWithLevel:@"some level" data:data];

where [CookieManager summary] returns a string

**Comment by rokob** [comment]
I just made a new app with this exact code, where I made the following class to fill in for `CookieManager` which returns a string:

```objc
@interface CookieManager : NSObject
+(NSString *)summary;
@end

@implementation CookieManager
+ (NSString *)summary {
    return @"bork bork";
}
@end
```

I see the error in my rollbar dashboard. Are you sure that you called:

```objc
[Rollbar initWithAccessToken:@"..."]
```

I don't see a crash when I leave out that line, but it does not get sent to rollbar because the access token is missing.

What is the stack trace for the crash you are getting?

**Comment by freddyh** [comment]
![screen shot 2017-04-26 at 2 47 26 pm](https://cloud.githubusercontent.com/assets/307890/25490897/2742a9c4-2b23-11e7-9537-b4009972e595.png)

**Comment by freddyh** [comment]
Consider attempting to send cookie properties to Rollbar:

```
// Fetch cookies
NSArray<NSHTTPCookie*>* cookies = [[NSHTTPCookieStorage sharedHTTPCookieStorage] cookies];

// Assuming there is at least one cookie
NSHTTPCookie* firstCookie = [cookies firstObject];

// This dictionary will contain a key value pair where the value is a NSDate object.
// NSDate object does pass `isValidJSONObject` so the application will crash
NSDictionary* cookieProperties = [firstCookie properties];

// Let Rollbar take the wheel
[Rollbar infoWithMessage:messageName data:cookieProperties];
```

Should be fixed by:
https://github.com/rollbar/rollbar-ios/pull/54
