### ISSUE TITLE
Wrong code_version on ios

### ISSUE THREAD

**Issue by karimkazoo** [rollbar/rollbar-ios#48]
Hello, I'm working on a react native app and I have some issues with the code_version retrieved.

When i'm opening an item on my account on rollbar.com, I can see

`client.ios.short_version: 1.6.1`

And that is the version users see an the app store.

But I have an issue with this value

`code_version : 19 `

This is the value used when I click on "resolved in" for an item.

So my issue is the following: how can I use the short version as the code version ? 

In the `RollbarNotifier.m` file we can see these lines of code :

`@"code_version"` refers to `NSString *version = [mainBundle objectForInfoDictionaryKey:(NSString*)kCFBundleVersionKey];`

Instead I would prefer to use 

`NSString *shortVersion = [mainBundle objectForInfoDictionaryKey:@"CFBundleShortVersionString"];`

**Comment by rokob** [comment]
This is confusing to me as well. We need to figure this out and have a good story for it. I think part of this is a backend UI issue, but we need to ensure we are sending the relevant versions from the SDK. Adding to the v1 milestone to ensure we handle this.

**Comment by karimkazoo** [comment]
Nice ! Thanks !

**Comment by rokob** [comment]
Okay I've done a bit more digging into this to see how we can work with this. We use what is currently called "code_version" (i.e. kCFBundleVersionKey) because it is tied to your dsym and therefore how we do symbolication. So we have to have that value for looking up the dsym because you can have multiple builds (kCFBundleVersionKey numbers) for one human readable version (CFBundleShortVersionString). You are saying that you want to use `client.ios.short_version` as your resolved in version which would correspond to possibly many code_versions. One is more precise than the other, but I understand that almost no one ever deals with the build numbers.

To help that though, you simply want to be able to say "resolved in" using the human consumable 1.6.1 version identifier rather than build number 29?

**Comment by stevenremot** [comment]
Hello @rokob , I'm in the same team as @karimkazoo, I will give you a bit more insight. We can use the CFBundleVersionKey to resolve version and we will do it like this if that's necesary. The reason we tried to find an alternative is that we have a React Native app, so we get bugs for Android and iOS on the same project. This means we have to be careful to use the build number when we mark an iOS bug as resolved, and the semver version on Android.

Now that the React Native rollbar library is out, maybe the need is not relevant anymore, we didn't try it yet. Even if it's not the case, that's something we can accomodate 🙂
