### ISSUE TITLE
Add telemetry scrubbing options

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-ios#80]
Similar to rollbar.js scrubTelemetryInputs and telemetryScrubber

**Comment by akornich** [comment]
@rivkahstandig3636 and @jessewgibbs, can I have a bit more details on how these settings are expected to behave?

**Comment by rivkahstandig3636** [comment]
Sure, what is unclear? Have you checked out the docs for it in rollbar.js?

**Comment by akornich** [comment]
@rivkahstandig3636 and @jessewgibbs, I added telemetry inputs scrubbing option, however here are the main differences compare to javascript's implementation:
1. it looks like Rollbar-iOS SDK uses telemetry ViewEvent instead of telemetry DOM event (as in javascript SDK)
2. if I attempt to send a mock ViewEvent from a unit test to Rollbar API, the Rollbar Dashboard fails to render telemetry events for the item (I think @rivkahstandig3636 already forwarded this info to the UI team some time ago)
I'll be merging shortly the PR with this current implementation but we may have to follow it up is some corrections as needed.

**Comment by rivkahstandig3636** [comment]
That's fine, thank you @akornich! I did pass on that bug to the rest of the team when you first reported it to me :)
